### PR TITLE
Gm frrouting

### PR DESCRIPTION
**Pull request by gmorrell**
Update playbooks and config files for each demo to use FRR. The Quagga versions no longer worked:

fatal: [leaf02]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service quagga: host"}
fatal: [spine01]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service quagga: host"}
fatal: [spine02]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service quagga: host"}
fatal: [leaf01]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service quagga: Job for quagga.service failed. See 'systemctl status quagga.service' and 'journalctl -xn' for details.\n"}

Now works.

### CODE REVIEW

**Comment by gmorrell** [comment]
Hi Eric. Done, I think. I'm new to Git so apologies for not realising a rename must be followed by an add!

**Comment by ericpulvino** [comment]
In the process of reviewing this now.

**Comment by ericpulvino** [comment]
Thank you @gmorrell !

**Comment by gmorrell** [comment]
You're welcome! @ollyg did most of the groundwork here: https://github.com/ollyg/cldemo-config-mlag

**Pull request merged**
