### PR TITLE
Update pushconfig to remove hostname requirement

### PR DESCRIPTION
**Pull request by plumbis**
This PR assumes that pushconfig should run against all hosts. This removes the second command line argument and updates the error message to be helpful.

The readme was also updated to correct references to the script.

### CODE REVIEW

**Comment by trapier** [comment]
I frequently bring up a subset of nodes.  Would it be possible to add a handler that produces a short error message instead of the DNS lookup traceback that occurs when a node isn't up?

**Comment by plumbis** [comment]
@trapier I updated this PR to wrap the SSH connection in a try/except to eliminate the traceback. I also changed the argument handling to allow you to specify arguments like the old style. no arguments assumes it should be pushed across all devices.

**Comment by isharacomix** [comment]
The only change I have a problem with is removing the topology diagram. Remember that the reference topology has many redundant cables. In this demo, for example, even though the reference topology specifies that hosts are dual attached, in this demo they are "single attached" by leaving the second interface down. The demo needs to specify *which subset of the reference topology is relevant*.

I'm not entirely opposed to a "default" second argument, but where did this come from?

**Comment by isharacomix** [comment]
As an aside, you left out "server03" and "server04" from default args. I assume this change gracefully fails when only a subset of the topology is up?

**Comment by plumbis** [comment]
The missing servers were added. This does not improve any previous error handling when only part of the topology was up. This would need to be handled as a separate PR.

**Pull request closed without merging**
